import IndexLoading from './components/loading/IndexLoading'
import { AeoninkFont } from './font/font'
import Header from './components/header/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './app.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={AeoninkFont.className}>
        <Header />
        <IndexLoading />
        {children}
      </body>
    </html>
  )
}
